[server]
runOnSave = true
headless = true
sslCertFile = "/mnt/beta/share/kun_workspace/settings/certificate/server.crt"
sslKeyFile = "/mnt/beta/share/kun_workspace/settings/certificate/server.key"
port = 5002

[browser]
gatherUsageStats = false
